# Generated by Django 4.1.4 on 2023-01-31 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('created_fild', models.DateTimeField(auto_now_add=True, verbose_name='Дата подключения датчика')),
                ('update_fild', models.DateTimeField(auto_now=True, verbose_name='Дата обновления датчика')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('created_fild', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения показаний')),
                ('update_fild', models.DateTimeField(auto_now=True, verbose_name='Дата обновления датчика')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor')),
            ],
        ),
    ]
